### PR TITLE
PFA-272: Screen modes feature

### PR DESCRIPTION
**Pull request by TheMankel**
### This PR adds "Theater" and "Full screen" modes

**Preview:**

https://github.com/Nospoko/streamlit-pianoroll/assets/26410548/e39b6252-50e0-43cc-866e-2b0885e900a4

---
[Task link](https://sacrebleu.atlassian.net/browse/PFA-272)

### CODE REVIEW

**Comment by TheMankel** [comment]
I added both modes. Let me know if this is something you had in mind. I have a question about the "theater" mode - for now, the iframe in streamlit limits the size of the whole component and therefore is not rendered from the left to right edge of the viewport, but in the frontend view it is set to stretch into the viewport. Should I try to figure out how to extend the iframe in streamlit as well?

By the way, the red background color in the theater mode is only for development, because with black I am not able to see the dimensions of the component as it blends with the background 🙈 


https://github.com/Nospoko/streamlit-pianoroll/assets/26410548/25b1294b-a1d6-4329-a097-a78e228e86b6

**Comment by roszcz** [comment]
It should be fine with the theater mode using the streamlits iframe - I would stretch the pianoroll svg to the full width in place where now there's red :)

**Comment by roszcz** [comment]
- [ ] I think we can make the "theater mode" default for this element - can you adjust it so it always uses the full available frame for the svg element?
- [ ] For the full screen, can you move the button to be on the pianoroll element? It can be the same as in the youtube player, including the "Full screen" text showing up on hover :)
- [ ] There's some inconsistency before and after making an element full screen:

Before:

image

After (going full screen and back with Esc button):

image

**Comment by TheMankel** [comment]
Should be fixed by now. Let me know if the fullscreen button design looks the way you wanted. One thing - the video recorder was still able to record the pointer, even though it is invisible when the mouse is inactive and in range of the pianoroll player (just like on youtube)

https://github.com/Nospoko/streamlit-pianoroll/assets/26410548/4562bf29-c7a1-4d17-b712-f4411a121c0c

I think currently the code associated with handling this UI is too large to keep it still in the `main.ts` file, so I would like to create a separate class in new file to handle these modes. Let me know what you think about this

**Comment by roszcz** [comment]
> I think currently the code associated with handling this UI is too large to keep it still in the main.ts file, so I would like to create a separate class in new file to handle these modes. Let me know what you think about this

Go for it 💪 

I think that quitting the full screen with Esc flips the button state (first the square is for full screen, I clicked the cross to exit full screen, clicked the square again to go full screen, pressed Esc - and then there's the cross icon where square used to be):

https://github.com/Nospoko/streamlit-pianoroll/assets/8056825/51bb767a-5179-429c-8b3e-21968803cad4

I also have issues with the piano roll disappearing when going back from the full screen (this only happens with the three piano rolls in a row):

https://github.com/Nospoko/streamlit-pianoroll/assets/8056825/686c26a1-7c7c-4bbd-aa03-4a87accf08b7

Let me know if you can reproduce these, could be something environment specific 🤔

**Comment by TheMankel** [comment]
The missing icon change after exiting fullscreen mode with the escape button was my mistake. I just added one line that fixes it.

I was able to reproduce the bug with the disappearing piano roll. From what I noticed, sometimes after exiting fullscreen, the height of the iframe is set to 0, so it seems to have disappeared. I've added the line `Streamlit.setFrameHeight()` to the code that handles the full screen exit, but I'm not 100% sure if that fixes it, since it's something new to me. After adding this line, the problem never appeared again, but this bug doesn't occur very often, so I'll try to test it every time I code.

image

I will refactor the code into a separate class in the next few days, as I do not want to neglect other tasks 🙈

**Review by roszcz — APPROVED** [review]

**Pull request merged**
